// AutoFlip Business Core — protected deals, economy, goals and service development.
(function(){
  'use strict';
  var busy=new Set(),lastServiceNotice='';
  var CITY={
    'Москва':{buy:1.05,demand:1.08,event:'Спрос на бизнес-класс'},'Санкт-Петербург':{buy:1.03,demand:1.05,event:'Спрос на европейские марки'},
    'Нижний Новгород':{buy:.97,demand:1,event:'Неделя семейных авто'},'Екатеринбург':{buy:1.01,demand:1.04,event:'Спрос на кроссоверы'},
    'Киров':{buy:.92,demand:.96,event:'Дешёвые проекты'},'Краснодар':{buy:1.02,demand:1.04,event:'Сезон кабриолетов'},
    'Пермь':{buy:.96,demand:1,event:'Спрос на полный привод'},'Калининград':{buy:1.01,demand:1.06,event:'Редкие европейские авто'},
    'Сургут':{buy:1.08,demand:1.11,event:'Высокий спрос на внедорожники'},'Чита':{buy:.94,demand:1.03,event:'Японский рынок'},
    'Казань':{buy:1.02,demand:1.07,event:'Активный рынок седанов'},'Владивосток':{buy:.98,demand:1.1,event:'Редкие праворульные авто'},
    'Ярославль':{buy:.96,demand:.99,event:'Спрос на бюджетные авто'},'Ростов':{buy:1,demand:1.05,event:'Южный авторынок'},
    'Махачкала':{buy:1.01,demand:1.08,event:'Спрос на мощные седаны'},'Уфа':{buy:.98,demand:1.02,event:'Спрос на универсалы'},
    'Воронеж':{buy:.97,demand:1.01,event:'Неделя доступных авто'},'Оренбург':{buy:.95,demand:1,event:'Спрос на внедорожники'},
    'Тверь':{buy:.95,demand:.99,event:'Выгодные проекты'},'Самара':{buy:.98,demand:1.03,event:'Активный вторичный рынок'}
  };
  function total(){return Number(state.gameClock&&state.gameClock.total||0);}
  function day(){return Math.floor(total()/1440)+1;}
  function nowText(){try{return new Date().toLocaleString('ru-RU',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'});}catch(e){return '';}}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function persistEconomy(){try{if(typeof persist==='function')persist();else if(typeof save==='function')save();else localStorage.setItem(KEY,JSON.stringify(state));}catch(e){}}
  function key(car){return car&&(car._garageId||car.listingId||['car',car.id,car.name,car.buy].join('-'));}
  function ensure(){
    if(!state.economy||typeof state.economy!=='object')state.economy={};var e=state.economy;e.version=3;
    ['appliedIds','transactions','soldModels','collection','achievements','repeatClients','notified','history'].forEach(function(k){if(!Array.isArray(e[k]))e[k]=[];});
    if(!e.service||typeof e.service!=='object')e.service={tools:0,lift:0,workers:0,partsStock:0,rating:5,reviews:[]};
    e.service.tools=Math.max(0,Math.min(2,Number(e.service.tools||0)));e.service.lift=Math.max(0,Math.min(2,Number(e.service.lift||0)));e.service.workers=Math.max(0,Math.min(2,Number(e.service.workers||0)));e.service.rating=Math.max(1,Math.min(5,Number(e.service.rating||5)));
    if(!e.goals||typeof e.goals!=='object')e.goals={};
    var d=day(),week=Math.floor((d-1)/7)+1;
    if(e.goals.day!==d)e.goals.daily={day:d,claimed:false,targets:[{id:'inspect',label:'Проверить документы или провести диагностику',need:1,value:0},{id:'travel',label:'Совершить одну поездку',need:1,value:0},{id:'deal',label:'Завершить одну сделку',need:1,value:0}]};
    if(e.goals.week!==week){e.goals.weekly={week:week,claimed:false,targets:[{id:'deal',label:'Завершить 5 сделок',need:5,value:0},{id:'profit',label:'Заработать 300 000 ₽ чистыми',need:300000,value:0},{id:'service',label:'Выполнить 2 заказа сервиса',need:2,value:0}]};e.goals.clan={week:week,value:0,need:10,claimed:false};}
    if(!e.goals.clan)e.goals.clan={week:week,value:0,need:10,claimed:false};
    if(!e.regionalEvent||e.regionalEvent.day!==d){var names=Object.keys(CITY),city=names[(d*7)%names.length],active=d%4===0;e.regionalEvent={day:d,active:active,city:city,title:active?'Редкий автовоз прибыл в город':'Обычный торговый день',factor:active?.94:1};if(active)notify('Города','✨','Редкое событие в '+city+': '+e.regionalEvent.title+'.','economy','regional-'+d);}
    e.goals.day=d;e.goals.week=week;e.transactions=e.transactions.slice(-150);e.appliedIds=e.appliedIds.slice(-300);e.notified=e.notified.slice(-100);e.history=e.history.slice(-200);return e;
  }
  function addGoal(id,value){var e=ensure();[e.goals.daily,e.goals.weekly].forEach(function(group){(group.targets||[]).forEach(function(t){if(t.id===id)t.value=Math.max(0,Number(t.value||0)+Number(value||1));});});if((id==='deal'||id==='service')&&e.goals.clan)e.goals.clan.value+=Number(value||1);}
  function notify(app,icon,text,route,k){if(typeof pushPhoneNotification==='function')pushPhoneNotification(app,icon,text,route,k);}
  function record(type,amount,data,id){var e=ensure();e.transactions.push({id:id||type+'-'+Date.now(),type:type,amount:Number(amount||0),day:day(),at:Date.now(),text:data&&data.text||'',car:data&&data.car||'',city:data&&data.city||state.city});persistEconomy();}
  function profile(car){
    if(!car)return null;if(car.autoFlipHistory)return car.autoFlipHistory;
    var seed=Math.abs(Number(car.id||0)*31+Number(car.year||0)*7+String(car.name||'').length*19+Math.round(Number(car.km||0)/1000));
    var owners=1+seed%5,accidents=seed%9===0?2:(seed%4===0?1:0),rollback=seed%11===0,restricted=seed%37===0;
    car.autoFlipHistory={vin:'AF'+String(seed*7919).padStart(12,'0').slice(-12),owners:owners,accidents:accidents,odometerRollback:rollback,documents:restricted?'Ограничение регистрации':'Чистые',documentsChecked:false,sellerPersonality:['Спокойный','Торгаш','Спешит продать','Дотошный'][seed%4],sellerHonesty:restricted||accidents?Math.max(25,75-seed%45):85+seed%15,events:[]};
    return car.autoFlipHistory;
  }
  window.AUTOFLIP_ENSURE_CAR_PROFILE=profile;
  window.AUTOFLIP_MODEL_DEMAND_FACTOR=function(car){var model=String(car&&car.name||''),cut=day()-7,count=ensure().soldModels.filter(function(x){return x.model===model&&x.day>=cut;}).length,modelFactor=Math.max(.70,[1,.96,.90,.82][Math.min(3,count)]||(.78-count*.02)),city=(CITY[car&&car.city]||{demand:1}).demand;return Math.max(.68,Math.min(1.12,modelFactor*city));};
  window.AUTOFLIP_CITY_MARKET_FACTOR=function(city,car){var c=CITY[city]||{buy:1,demand:1},event=ensure().regionalEvent;var rare=/Toyota|Subaru|Nissan|Lexus/.test(car&&car.name||'')&&city==='Владивосток';return c.buy*(rare?.92:1)*(event.active&&event.city===city?event.factor:1);};
  window.AUTOFLIP_CAR_VALUE=function(car,base){var h=profile(car),condition=car&&car.flipCondition,health=condition&&!condition.healthy&&!condition.repaired?.82:1;var history=(h.accidents?1-Math.min(.16,h.accidents*.07):1)*(h.odometerRollback?.92:1)*(h.documents==='Чистые'?1:.70);return Math.max(10000,Math.round(Number(base||car.market||car.buy||0)*health*history*window.AUTOFLIP_MODEL_DEMAND_FACTOR(car)/1000)*1000);};
  window.AUTOFLIP_DIAGNOSTIC_CHANCE=function(base){var s=ensure().service;return Math.min(.95,Number(base||0)+s.tools*.05+(Number(state.garageLevel||1)>=7?.05:0));};
  window.AUTOFLIP_UPDATE_LISTING=function(l,car,at){if(!l||!car)return false;var age=Math.floor((Number(at||total())-Number(l.createdAt||l.postedAt||at||total()))/1440),step=Math.max(0,Math.min(6,age-1));if(step<=Number(l.economyMarkdownStep||0))return false;var old=Number(l.ask||0),base=Number(l.originalAsk||old);l.originalAsk=base;l.economyMarkdownStep=step;l.ask=Math.max(10000,Math.round(base*(1-step*.02)/1000)*1000);profile(car).events.unshift('Цена объявления снижена после '+age+' дн. продажи');notify('Продажа','📉',car.name+': цена снижена до '+money(l.ask)+'.','economy','markdown-'+l.id+'-'+step);return old!==l.ask;};
  window.AUTOFLIP_PICK_BUYER_PROFILE=function(car,l,profiles){var e=ensure(),saved=e.repeatClients.filter(function(x){return x.model===car.name;});if(saved.length&&Math.random()<.35){var r=saved[Math.floor(Math.random()*saved.length)];return Object.assign({},profiles[0],{name:r.name,icon:'⭐',kind:'Постоянный клиент',offer:1,max:1,text:'Снова к тебе — прошлой сделкой остался доволен.'});}return profiles[Math.floor(Math.random()*profiles.length)];};
  window.AUTOFLIP_CONFIRM_ECONOMY=async function(id,type,amount,payload){
    var response=await fetch('/api/economy/confirm',{method:'POST',headers:{'content-type':'application/json'},credentials:'same-origin',body:JSON.stringify(Object.assign({transactionId:id,type:type,amount:Math.round(Number(amount||0))},payload||{}))});
    var body={};try{body=await response.json();}catch(e){}if(!response.ok||!body.ok)throw new Error(body.error||'Сервер не подтвердил операцию');return body;
  };
  function meetingAmount(m){return Math.max(0,Math.round(Number(m&&m.price||0)));}
  function acquired(before){return (state.cars||[]).find(function(c){return before.indexOf(c)<0;});}
  function afterDeal(m,before,beforeMoney,id){
    var e=ensure(),car=acquired(before),delta=Number(state.money||0)-beforeMoney,h=car&&profile(car);e.appliedIds.push(id);addGoal('deal',1);if(delta>0)addGoal('profit',delta);
    if(car){if(e.collection.indexOf(car.name)<0)e.collection.push(car.name);h.events.unshift('Куплен игроком в '+m.city+' · день '+day());
      var bad=car.flipCondition&&!car.flipCondition.healthy&&!car.flipCondition.repaired,fully=m.diagnostic&&m.diagnostic.mode==='full';if(bad&&!fully){var extra=Math.max(3000,Math.round((Number(car.flipCondition.cost||car.repair||10000))*(.08+Math.random()*.12)/1000)*1000);car.unplannedCost=Number(car.unplannedCost||0)+extra;car.needsTow=true;h.events.unshift('После покупки потребовались эвакуатор и внеплановые работы: '+money(extra));notify('Гараж','⚠️',car.name+': после покупки обнаружены дополнительные расходы '+money(extra)+'.','economy','extra-'+id);}}
    if(m.side==='buyer'){var sold=before.find(function(c){return !(state.cars||[]).some(function(x){return key(x)===key(c);});});if(sold){profile(sold).events.unshift('Продан игроком · день '+day());e.soldModels.push({model:sold.name,day:day(),price:m.price});if(Math.random()<.28)e.repeatClients.push({name:m.person,model:sold.name,day:day()});}}
    record(m.kind.indexOf('purchase')>=0?'purchase':m.kind.indexOf('trade')>=0?'exchange':'sale',Math.abs(delta),{car:m.carName,city:m.city,text:'Встреча '+m.carName},id);persistEconomy();
  }
  var rawMeeting=window.completeMeeting;
  if(typeof rawMeeting==='function')window.completeMeeting=async function(id){
    var m=(state.meetings||[]).find(function(x){return x.id===id;});if(!m||m.status!=='scheduled'||busy.has(id))return typeof openMeeting==='function'?openMeeting(id):null;
    var tx='meeting:'+id,e=ensure();if(e.appliedIds.indexOf(tx)>=0)return typeof openMeeting==='function'?openMeeting(id):null;busy.add(id);
    try{var type=m.kind.indexOf('purchase')>=0?'purchase':m.kind.indexOf('trade')>=0?'exchange':'sale';await window.AUTOFLIP_CONFIRM_ECONOMY(tx,type,meetingAmount(m),{car:m.carName,city:m.city,sourceId:m.sourceId});var before=(state.cars||[]).slice(),cash=Number(state.money||0);rawMeeting(id);if(m.status==='completed')afterDeal(m,before,cash,tx);}
    catch(error){alert('Сделка не проведена: '+error.message+'. Прогресс и деньги не изменились. Проверь интернет и повтори.');}
    finally{busy.delete(id);}
  };
  window.economyCheckDocuments=function(id){var m=(state.meetings||[]).find(function(x){return x.id===id;}),car=m&&(m.payload&&m.payload.car);if(!m||!car)return;var h=profile(car),cost=3500;if(h.documentsChecked)return openMeeting(id);if(Number(state.money||0)<cost)return alert('Для проверки документов нужно '+money(cost)+'.');state.money-=cost;h.documentsChecked=true;addGoal('inspect',1);record('cost',cost,{car:car.name,text:'Проверка документов'});persistEconomy();openMeeting(id);};
  var rawOpenMeeting=window.openMeeting;
  if(typeof rawOpenMeeting==='function')window.openMeeting=function(id){var result=rawOpenMeeting.apply(this,arguments),m=(state.meetings||[]).find(function(x){return x.id===id;}),car=m&&m.payload&&m.payload.car;if(car&&m.status==='scheduled'&&typeof document!=='undefined'){var h=profile(car),button=document.querySelector('.meeting-buy-confirm');if(button){var clues=h.sellerHonesty<60?'Продавец торопит и уклоняется от вопросов. Стоит всё проверить.':'Продавец отвечает спокойно, но документы всё равно лучше проверить.';button.insertAdjacentHTML('beforebegin','<section class="economy-check"><small>ИСТОРИЯ И ДОКУМЕНТЫ</small><b>'+esc(h.sellerPersonality)+'</b><p>'+esc(clues)+'</p>'+(h.documentsChecked?'<strong class="'+(h.documents==='Чистые'?'ok':'bad')+'">'+esc(h.documents)+'</strong>':'<button onclick="economyCheckDocuments(\''+esc(id)+'\')">Проверить документы · 3 500 ₽</button>')+'</section>');if(h.documentsChecked&&h.documents!=='Чистые'){button.disabled=true;button.textContent='Покупка заблокирована: '+h.documents;}}}return result;};
  var rawDiag=window.runMeetingDiagnostic;if(typeof rawDiag==='function')window.runMeetingDiagnostic=function(){var result=rawDiag.apply(this,arguments);addGoal('inspect',1);persistEconomy();return result;};
  var rawSaleValue=window.saleValue;if(typeof rawSaleValue==='function')window.saleValue=function(car){return window.AUTOFLIP_CAR_VALUE(car,rawSaleValue(car));};
  var rawSell=window.sellCar;if(typeof rawSell==='function')window.sellCar=function(){var car=state.car;if(car&&(car.needsTow||Number(car.unplannedCost||0)>0))return economyCarCosts(key(car));return rawSell.apply(this,arguments);};
  window.economyCarCosts=function(carKey){var car=(state.cars||[]).find(function(c){return key(c)===carKey;});if(!car)return garage();var due=Number(car.unplannedCost||0)+(car.needsTow?Math.max(5000,Math.round(Number(car.market||car.buy||0)*.012/1000)*1000):0);render('<div class="app economy-app">'+head('Подготовка автомобиля')+'<section class="economy-alert"><span>⚠️</span><h2>'+esc(car.name)+'</h2><p>После рискованной покупки машина не готова к продаже.</p></section><div class="economy-cost"><span>Эвакуатор и дополнительные работы</span><b>'+money(due)+'</b></div><button class="action green" onclick="economyPayCarCosts(\''+esc(carKey)+'\')">Оплатить и доставить</button><button class="action" onclick="garage()">Назад</button></div>');};
  window.economyPayCarCosts=function(carKey){var car=(state.cars||[]).find(function(c){return key(c)===carKey;});if(!car)return garage();var due=Number(car.unplannedCost||0)+(car.needsTow?Math.max(5000,Math.round(Number(car.market||car.buy||0)*.012/1000)*1000):0);if(Number(state.money||0)<due)return alert('Не хватает '+money(due-Number(state.money||0))+'.');state.money-=due;car.unplannedCost=0;car.needsTow=false;profile(car).events.unshift('Оплачены эвакуатор и внеплановые работы: '+money(due));record('cost',due,{car:car.name,text:'Эвакуатор и внеплановый ремонт'});persistEconomy();garage();};
  var rawDetails=window.garageCarDetails;if(typeof rawDetails==='function')window.garageCarDetails=function(index){var r=rawDetails.apply(this,arguments),car=(state.cars||[])[index];if(car&&typeof document!=='undefined'){var h=profile(car),app=document.querySelector('.garage-app');if(app)app.insertAdjacentHTML('beforeend','<section class="economy-history"><small>ИСТОРИЯ АВТОМОБИЛЯ</small><div><span>VIN</span><b>'+esc(h.vin)+'</b></div><div><span>Владельцев</span><b>'+h.owners+'</b></div><div><span>ДТП</span><b>'+h.accidents+'</b></div><div><span>Пробег</span><b>'+(h.odometerRollback?'Есть признаки скрутки':'Без замечаний')+'</b></div><div><span>Документы</span><b>'+esc(h.documentsChecked?h.documents:'Не проверены')+'</b></div>'+(h.events.length?'<p>'+h.events.slice(0,4).map(esc).join('<br>')+'</p>':'')+'</section>');}return r;};
  function service(){return ensure().service;}
  var rawTake=window.garageTakeServiceJob;if(typeof rawTake==='function')window.garageTakeServiceJob=function(id){var g=state.garageProgress||{},job=(g.serviceRequests||[]).find(function(x){return x.id===id;}),before=Number(state.money||0),r=rawTake.apply(this,arguments);if(g.activeServiceJob&&job&&g.activeServiceJob.id===id){var s=service(),speed=s.workers===1?.05:s.workers===2?.15:0,discount=Math.min(Number(s.partsStock||0),Math.round(Number(job.parts||0)*.10/1000)*1000);if(discount>0){s.partsStock-=discount;state.money=Number(state.money||0)+discount;g.activeServiceJob.parts=Math.max(0,Number(g.activeServiceJob.parts||0)-discount);}g.activeServiceJob.finishAt=g.activeServiceJob.startedAt+g.activeServiceJob.hours*3600000*(1-speed);g.activeServiceJob.extraRisk=Math.max(.03,.16-s.tools*.04-s.lift*.03);record('service_parts',Math.max(0,before-Number(state.money||0)),{car:job.car,text:'Детали для заказа'});persistEconomy();garageService();}return r;};
  var rawServiceComplete=window.garageCompleteServiceJob;if(typeof rawServiceComplete==='function')window.garageCompleteServiceJob=async function(){var g=state.garageProgress||{},job=g.activeServiceJob;if(!job||Date.now()<Number(job.finishAt||0)||busy.has(job.id))return rawServiceComplete.apply(this,arguments);var tx='service:'+job.id;if(ensure().appliedIds.indexOf(tx)>=0)return garageService();busy.add(job.id);try{if(!job.riskResolved){job.riskResolved=true;job.extraProblem=Math.random()<Number(job.extraRisk||.12)?'Во время ремонта обнаружилась дополнительная неисправность':'';if(job.extraProblem){var penalty=Math.round(Number(job.payout||0)*.18/1000)*1000;job.payout=Math.max(job.parts,Number(job.payout||0)-penalty);}persistEconomy();}var failed=!!job.extraProblem,payout=Number(job.payout||0),profit=payout-Number(job.parts||0);await window.AUTOFLIP_CONFIRM_ECONOMY(tx,'service',payout,{car:job.car,sourceId:job.id});rawServiceComplete();var s=service(),stars=failed?4:5;s.rating=Math.max(1,Math.min(5,(s.rating*(s.reviews.length||1)+stars)/((s.reviews.length||1)+1)));s.reviews.unshift({name:job.name,stars:stars,text:failed?'Сделали, но пришлось ждать дополнительную деталь.':'Всё сделали в срок, машина снова на ходу.',at:nowText()});s.reviews=s.reviews.slice(0,20);ensure().appliedIds.push(tx);addGoal('service',1);addGoal('profit',Math.max(0,profit));record('service',payout,{car:job.car,text:job.issue},tx);persistEconomy();}catch(error){alert('Выплату не подтвердил сервер: '+error.message+'. Заказ сохранён, можно повторить.');}finally{busy.delete(job.id);}};
  window.economyBuyServiceUpgrade=function(type){var s=service(),cfg={tools:[120000,280000],lift:[220000,520000],workers:[180000,450000]},list=cfg[type],level=Number(s[type]||0);if(!list||level>=2)return economyGarage();var cost=list[level];if(Number(state.money||0)<cost)return alert('Не хватает '+money(cost-Number(state.money||0))+'.');state.money-=cost;s[type]=level+1;record('investment',cost,{text:type});persistEconomy();economyGarage();};
  window.economyBuyParts=function(){var s=service(),cost=75000;if(Number(state.money||0)<cost)return alert('Не хватает '+money(cost-Number(state.money||0))+'.');state.money-=cost;s.partsStock=Number(s.partsStock||0)+100000;record('investment',cost,{text:'Склад запчастей'});persistEconomy();economyGarage();};
  function upCard(type,title,desc){var s=service(),level=Number(s[type]||0),prices={tools:[120000,280000],lift:[220000,520000],workers:[180000,450000]},cost=prices[type][level];return '<article><small>УРОВЕНЬ '+level+' / 2</small><b>'+title+'</b><p>'+desc+'</p>'+(level<2?'<button onclick="economyBuyServiceUpgrade(\''+type+'\')">Улучшить · '+money(cost)+'</button>':'<strong>Максимальный уровень</strong>')+'</article>';}
  window.economyGarage=function(){var s=service(),reviews=s.reviews||[];render('<div class="app economy-app">'+head('Бизнес гаража')+'<nav class="economy-tabs"><button onclick="economyHub()">Что дальше</button><button class="active">Гараж</button><button onclick="economyStats()">Экономика</button></nav><section class="economy-rating"><span>★</span><div><small>РЕЙТИНГ АВТОСЕРВИСА</small><h2>'+s.rating.toFixed(1)+' / 5</h2><p>'+reviews.length+' отзывов клиентов</p></div></section><div class="economy-upgrades">'+upCard('tools','Инструменты','+5% к качеству диагностики, ниже риск ошибки')+upCard('lift','Подъёмники','Ниже риск дополнительной поломки')+upCard('workers','Работники','Ускорение ремонта на 5% и 15%')+'<article><small>СКЛАД</small><b>Запчасти</b><p>Запас: '+money(s.partsStock||0)+'</p><button onclick="economyBuyParts()">Пополнить · 75 000 ₽</button></article></div><section class="economy-reviews"><h3>Отзывы клиентов</h3>'+(reviews.length?reviews.slice(0,5).map(function(x){return '<div><b>'+esc(x.name)+' · '+('★★★★★'.slice(0,x.stars))+'</b><p>'+esc(x.text)+'</p><small>'+esc(x.at)+'</small></div>';}).join(''):'<p>Первый отзыв появится после заказа.</p>')+'</section><button class="action" onclick="garageService()">Открыть автосервис</button></div>');};
  window.economyClaimGoal=function(kind){var e=ensure(),g=kind==='weekly'?e.goals.weekly:e.goals.daily;if(g.claimed||!g.targets.every(function(t){return t.value>=t.need;}))return;var reward=kind==='weekly'?125000:25000;g.claimed=true;state.money=Number(state.money||0)+reward;state.rep=Number(state.rep||0)+(kind==='weekly'?5:1);record('reward',reward,{text:kind==='weekly'?'Недельный контракт':'Ежедневные задания'});persistEconomy();economyHub();};
  window.economyClaimClanGoal=function(){var e=ensure(),g=e.goals.clan;if(!window.AUTOFLIP_COMMUNITY_ME||!window.AUTOFLIP_COMMUNITY_ME.clan||g.claimed||g.value<g.need)return;g.claimed=true;state.money=Number(state.money||0)+50000;state.rep=Number(state.rep||0)+2;record('reward',50000,{text:'Задание клана'});persistEconomy();economyHub();};
  function achievementData(){var e=ensure(),serviceJobs=Number(state.garageProgress&&state.garageProgress.stats&&state.garageProgress.stats.serviceJobs||0);return [{id:'first_deal',name:'Первая сделка',done:Number(state.deals||0)>=1},{id:'dealer_10',name:'Перекупщик',done:Number(state.deals||0)>=10},{id:'collector_10',name:'Коллекционер',done:e.collection.length>=10},{id:'service_10',name:'Мастер сервиса',done:serviceJobs>=10},{id:'rep_100',name:'Надёжное имя',done:Number(state.rep||0)>=100}];}
  function updateAchievements(){var e=ensure();achievementData().forEach(function(a){if(a.done&&e.achievements.indexOf(a.id)<0){e.achievements.push(a.id);state.money=Number(state.money||0)+15000;notify('Достижения','🏆','Открыто: '+a.name+'. Награда 15 000 ₽.','economy','achievement-'+a.id);}});}
  function goalBlock(title,g,kind,reward){var ready=g.targets.every(function(t){return t.value>=t.need;});return '<section class="economy-goals"><div><small>'+title+'</small><b>'+money(reward)+' + репутация</b></div>'+g.targets.map(function(t){var p=Math.min(100,Number(t.value||0)/t.need*100);return '<article><span>✓</span><div><b>'+esc(t.label)+'</b><i><em style="width:'+p+'%"></em></i><small>'+Math.min(t.value,t.need).toLocaleString('ru-RU')+' / '+t.need.toLocaleString('ru-RU')+'</small></div></article>';}).join('')+'<button '+(!ready||g.claimed?'disabled':'')+' onclick="economyClaimGoal(\''+kind+'\')">'+(g.claimed?'Награда получена':ready?'Забрать награду':'Выполняется')+'</button></section>';}
  function nextCard(icon,title,value,action){return '<button onclick="'+action+'"><span>'+icon+'</span><div><small>'+title+'</small><b>'+value+'</b></div><i>›</i></button>';}
  window.economyHub=function(){updateAchievements();var e=ensure(),meeting=(state.meetings||[]).filter(function(x){return x.status==='scheduled';}).sort(function(a,b){return a.at-b.at;})[0],g=state.garageProgress||{},job=g.activeServiceJob,listings=(state.activeListings||[]).filter(function(x){return x.status==='active';}),unread=(state.buyerInbox||[]).filter(function(x){return !x.read&&x.status!=='declined'&&x.status!=='sold';}).length,marketLeft=typeof liveMarketCountdownText==='function'?liveMarketCountdownText():'через несколько игровых часов';var cards='';cards+=meeting?nextCard('📅','Ближайшая встреча',esc(meeting.carName)+' · '+esc(meeting.city),"openMeeting('"+meeting.id+"')"):nextCard('📅','Встречи','Нет запланированных',"messages('meetings')");cards+=job?nextCard('🔧','Автосервис',Date.now()>=job.finishAt?'Ремонт завершён':esc(job.car)+' в работе','garageService()'):nextCard('🔧','Автосервис',g.level>=5?'Можно выбрать заказ':'Откроется на 5 уровне','garageService()');cards+=nextCard('🏷️','Машины на продаже',listings.length+' объявл.','garage()');cards+=nextCard('🏦','Банк',Number(state.loan||0)>0?'Долг '+money(state.loan):'Кредитов нет','autoBankHome()');cards+=nextCard('🚘','Рынок',marketLeft,'market()');cards+=nextCard('🏗️','Развитие гаража','Уровень '+Number(g.level||state.garageLevel||1),'garageProgress()');cards+=nextCard('💬','Непрочитанные сообщения',String(unread),'messages()');var clan=window.AUTOFLIP_COMMUNITY_ME&&window.AUTOFLIP_COMMUNITY_ME.clan,clanGoal=clan?'<section class="economy-goals"><div><small>ЗАДАНИЕ КЛАНА ['+esc(clan.tag)+']</small><b>50 000 ₽ + репутация</b></div><article><span>◆</span><div><b>Вместе завершить сделки и заказы</b><i><em style="width:'+Math.min(100,e.goals.clan.value/e.goals.clan.need*100)+'%"></em></i><small>'+Math.min(e.goals.clan.value,e.goals.clan.need)+' / '+e.goals.clan.need+'</small></div></article><button '+(e.goals.clan.value<e.goals.clan.need||e.goals.clan.claimed?'disabled':'')+' onclick="economyClaimClanGoal()">'+(e.goals.clan.claimed?'Награда получена':'Забрать награду')+'</button></section>':'';render('<div class="app economy-app">'+head('Что делать дальше')+'<section class="economy-hero"><small>ЦЕНТР УПРАВЛЕНИЯ</small><h2>Твой следующий ход</h2><p>Все важные дела, сроки и награды в одном месте.</p></section><nav class="economy-tabs"><button class="active">Что дальше</button><button onclick="economyGarage()">Гараж</button><button onclick="economyStats()">Экономика</button></nav><div class="economy-next">'+cards+'</div>'+goalBlock('ЗАДАНИЯ НА СЕГОДНЯ',e.goals.daily,'daily',25000)+goalBlock('НЕДЕЛЬНЫЙ КОНТРАКТ',e.goals.weekly,'weekly',125000)+clanGoal+'</div>');};
  window.economyStats=function(){var e=ensure(),groups={};e.transactions.forEach(function(x){if(!groups[x.type])groups[x.type]={count:0,sum:0};groups[x.type].count++;groups[x.type].sum+=x.amount;});var rows=Object.keys(groups).map(function(k){return '<div><span>'+esc({purchase:'Покупки',sale:'Продажи',exchange:'Обмены',service:'Автосервис',service_parts:'Детали сервиса',transport:'Транспорт',cost:'Расходы',investment:'Развитие',reward:'Награды'}[k]||k)+'</span><b>'+groups[k].count+'</b><strong>'+money(groups[k].sum)+'</strong></div>';}).join('');var city=CITY[state.city]||{buy:1,demand:1,event:'Обычный рынок'},event=e.regionalEvent;render('<div class="app economy-app">'+head('Экономика')+'<nav class="economy-tabs"><button onclick="economyHub()">Что дальше</button><button onclick="economyGarage()">Гараж</button><button class="active">Экономика</button></nav><section class="economy-city"><small>'+esc(state.city).toUpperCase()+'</small><h2>'+esc(event.active&&event.city===state.city?event.title:city.event)+'</h2><div><span>Цены покупки <b>'+Math.round(city.buy*100)+'%</b></span><span>Спрос <b>'+Math.round(city.demand*100)+'%</b></span></div><p>'+(event.active?'Сегодня редкое региональное событие проходит в '+esc(event.city)+'. ':'')+'Покупай там, где предложение дешевле, и продавай в городе с высоким спросом. Дорога и доставка учитываются отдельно.</p></section><section class="economy-ledger"><h3>Статистика экономики</h3>'+ (rows||'<p>Здесь появятся покупки, продажи, обмены, расходы и прибыль.</p>')+'</section><section class="economy-collection"><small>КОЛЛЕКЦИЯ МОДЕЛЕЙ</small><h3>'+e.collection.length+' уникальных авто</h3><p>'+esc(e.collection.slice(-12).join(' · ')||'Купи первый автомобиль, чтобы начать коллекцию.')+'</p><b>Сезонные очки: '+Math.round(Number(state.rep||0)*10+e.transactions.length*25)+'</b><h3>Витрина достижений</h3><p>'+achievementData().map(function(a){return (e.achievements.indexOf(a.id)>=0?'🏆 ':'🔒 ')+a.name;}).join(' · ')+'</p></section></div>');};
  function serviceNotice(){var g=state.garageProgress||{},job=g.activeServiceJob;if(job&&Date.now()>=Number(job.finishAt||0)&&lastServiceNotice!==job.id){lastServiceNotice=job.id;notify('Автосервис','🔧','Ремонт '+job.car+' завершён. Забери оплату.','service','service-ready-'+job.id);persistEconomy();}}
  var rawTrip=window.confirmWorldTrip;if(typeof rawTrip==='function')window.confirmWorldTrip=function(){var cash=Number(state.money||0),r=rawTrip.apply(this,arguments),spent=Math.max(0,cash-Number(state.money||0));if(spent){addGoal('travel',1);record('transport',spent,{city:state.city,text:'Поездка'});}return r;};
  ensure();(typeof startVisibleInterval==='function'?startVisibleInterval:function(fn,delay){return setInterval(fn,delay);})(serviceNotice,30000);persistEconomy();
})();
