(function(){
  'use strict';
  var catalog=[],paymentsEnabled=false,loading=false,notice='';
  var regions=['77','97','799','78','98','178','52','152','66','96','196','43','23','93','123','59','81','159','39','91','86','186','75','80','16','116','716','25','125','76','61','161','761','05','02','102','702','36','136','56','69','63','163','763'];
  var letters='АВЕКМНОРСТУХ';
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function rub(v){return Number(v||0).toLocaleString('ru-RU')+' ₽';}
  function saveStore(){if(typeof persist==='function')persist();else if(typeof save==='function')save();}
  function ensureStore(){if(!state.store||typeof state.store!=='object')state.store={};if(!Array.isArray(state.store.appliedOrderIds))state.store.appliedOrderIds=[];return state.store;}
  function activeBoost(){var until=Number(ensureStore().fastBuyersUntil||0),left=until-Date.now();if(left<=0)return '';var days=Math.floor(left/86400000),hours=Math.ceil((left%86400000)/3600000);return (days?days+' д. ':'')+hours+' ч.';}
  function categoryTitle(value){return {money:'Игровые деньги',plates:'Номера',boosts:'Ускорители',garage:'Развитие гаража'}[value]||value;}
  function icon(value){return {money:'₽',plates:'▰',boosts:'⚡',garage:'◆'}[value]||'✦';}
  function productCard(p){var target=p.code==='garage_5'?5:p.code==='garage_10'?10:0,owned=target&&Number(state.garageLevel||1)>=target;return '<article class="store-product '+esc(p.category)+'">'+(p.badge?'<em>'+esc(p.badge)+'</em>':'')+'<span>'+icon(p.category)+'</span><div><small>'+esc(categoryTitle(p.category))+'</small><h3>'+esc(p.title)+'</h3><p>'+esc(p.description)+'</p></div><button '+(!paymentsEnabled||owned?'disabled':'')+' onclick="storeCheckout(\''+esc(p.code)+'\')"><b>'+(owned?'✓':rub(p.price))+'</b><small>'+(owned?'Получено':paymentsEnabled?'Купить':'Настройка оплаты')+'</small></button></article>';}
  function renderStore(){
    var boost=activeBoost(),groups=['money','plates','boosts','garage'].map(function(category){var items=catalog.filter(function(p){return p.category===category;});return items.length?'<section class="store-group"><div class="store-group-title"><span>'+icon(category)+'</span><div><small>МАГАЗИН</small><h2>'+categoryTitle(category)+'</h2></div></div><div class="store-products">'+items.map(productCard).join('')+'</div></section>':'';}).join('');
    render('<div class="app store-app">'+head('Магазин')+'<section class="store-hero"><div><small>AUTOFLIP STORE</small><h2>Ускорь свой путь.</h2><p>Покупки навсегда сохраняются в аккаунте и выдаются только после подтверждения платежа.</p></div><span>AF</span></section>'+(boost?'<div class="store-boost-active"><span>⚡</span><div><b>Быстрые покупатели активны</b><small>Осталось '+esc(boost)+'</small></div></div>':'')+(notice?'<div class="store-notice">'+esc(notice)+'</div>':'')+(loading?'<div class="store-loading">Загружаем магазин…</div>':groups||'<div class="store-loading">Магазин временно недоступен</div>')+'<div class="store-security"><b>🔒 Безопасная оплата через ЮKassa</b><p>Данные карты не попадают в AutoFlip. Товар начисляется сервером после успешной оплаты и не выдаётся повторно.</p></div><button class="action" onclick="storeHistory()">История покупок</button></div>');
    notice='';
  }
  async function request(url,options){var response=await fetch(url,Object.assign({credentials:'same-origin',cache:'no-store'},options||{}));var data=await response.json().catch(function(){return {error:'network_error'};});if(!response.ok)throw new Error(data.error||('HTTP '+response.status));return data;}
  function errorText(code){return {payments_not_configured:'Платежи пока работают в режиме настройки. Подключим ключи ЮKassa перед тестом.',invalid_email:'Проверь адрес электронной почты.',invalid_plate:'Номер должен выглядеть так: А777АА.',invalid_plate_region:'Выбери регион из списка.',payment_provider_error:'ЮKassa временно не ответила. Деньги не списаны.',too_many_pending_orders:'Слишком много незавершённых оплат. Заверши одну из них или попробуй через 10 минут.',already_owned:'Эта привилегия уже куплена.',network_error:'Нет связи с сервером.'}[code]||'Не удалось выполнить действие. Попробуй ещё раз.';}
  window.openStore=async function(){loading=true;renderStore();try{var data=await request('/api/store/catalog');catalog=data.products||[];paymentsEnabled=!!data.paymentsEnabled;await syncStoreOrders();}catch(error){notice=errorText(error.message);}finally{loading=false;renderStore();}};
  window.storeCheckout=function(code){var p=catalog.find(function(x){return x.code===code;});if(!p)return openStore();if(!paymentsEnabled){notice=errorText('payments_not_configured');return renderStore();}var custom=p.code==='plate_custom'?'<div class="store-plate-builder"><label>Буква<select id="storeLetter1">'+[...letters].map(function(x){return '<option>'+x+'</option>';}).join('')+'</select></label><label>Цифры<input id="storeDigits" inputmode="numeric" maxlength="3" value="777"></label><label>Буквы<div><select id="storeLetter2">'+[...letters].map(function(x){return '<option>'+x+'</option>';}).join('')+'</select><select id="storeLetter3">'+[...letters].map(function(x){return '<option>'+x+'</option>';}).join('')+'</select></div></label><label>Регион<select id="storeRegion">'+regions.map(function(x){return '<option>'+x+'</option>';}).join('')+'</select></label></div>':'';render('<div class="app store-app">'+head('Оформление')+'<section class="store-checkout"><small>'+esc(categoryTitle(p.category))+'</small><span>'+icon(p.category)+'</span><h2>'+esc(p.title)+'</h2><p>'+esc(p.description)+'</p><strong>'+rub(p.price)+'</strong></section>'+custom+'<label class="store-email">Электронная почта для чека<input id="storeEmail" type="email" autocomplete="email" placeholder="name@example.ru"></label><div class="store-pay-note">Нажимая «Перейти к оплате», ты перейдёшь на защищённую страницу ЮKassa. Покупка привяжется к текущему аккаунту AutoFlip.</div><button id="storePayButton" class="action green" onclick="startStorePayment(\''+esc(p.code)+'\')">Перейти к оплате · '+rub(p.price)+'</button><button class="action" onclick="openStore()">Отмена</button></div>');};
  window.startStorePayment=async function(code){var button=document.getElementById('storePayButton'),email=document.getElementById('storeEmail');if(button)button.disabled=true;var payload={productCode:code,email:email&&email.value,clientToken:(crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(16).slice(2))};if(code==='plate_custom'){var digits=String(document.getElementById('storeDigits').value||'');if(!/^\d{3}$/.test(digits)){alert('Введи ровно три цифры.');if(button)button.disabled=false;return;}payload.customPlate={number:document.getElementById('storeLetter1').value+digits+document.getElementById('storeLetter2').value+document.getElementById('storeLetter3').value,region:document.getElementById('storeRegion').value};}try{var data=await request('/api/store/create-payment',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});localStorage.setItem('autoflip-store-order',data.orderId);if(data.confirmationUrl)location.assign(data.confirmationUrl);else{notice='Платёж уже обработан. Проверяем покупку…';await checkStoreOrder(data.orderId);}}catch(error){alert(errorText(error.message));if(button)button.disabled=false;}};
  function applyOrder(order){if(!order||order.status!=='paid')return false;var store=ensureStore();if(store.appliedOrderIds.indexOf(order.id)>=0)return false;var code=order.productCode;if(code==='cash_200k')state.money=Number(state.money||0)+200000;if(code==='cash_1m')state.money=Number(state.money||0)+1000000;if(code==='cash_2m')state.money=Number(state.money||0)+2000000;var durations={buyers_1d:86400000,buyers_7d:604800000,buyers_30d:2592000000};if(durations[code])store.fastBuyersUntil=Math.max(Date.now(),Number(store.fastBuyersUntil||0))+durations[code];var levels={garage_5:5,garage_10:10};if(levels[code]){if(!state.garageProgress||typeof state.garageProgress!=='object')state.garageProgress={};state.garageProgress.level=Math.max(Number(state.garageProgress.level||state.garageLevel||1),levels[code]);state.garageLevel=state.garageProgress.level;}if(code==='plate_cool'||code==='plate_custom'){if(!state.plates||typeof state.plates!=='object')state.plates={items:[],nextId:1};if(!Array.isArray(state.plates.items))state.plates.items=[];var custom=order.customPayload||{},number=custom.number;if(!number){var seed=order.id.replace(/-/g,''),d=['111','222','333','444','555','666','888','999'],a=letters.charAt(parseInt(seed.slice(0,2),16)%letters.length);number=a+d[parseInt(seed.slice(2,4),16)%d.length]+a+a;}var region=custom.region||regions[parseInt(order.id.replace(/-/g,'').slice(-2),16)%regions.length],cities=(window.AUTOFLIP_WORLD&&window.AUTOFLIP_WORLD.cities)||[],city=(cities.find(function(c){return c.regions.indexOf(region)>=0;})||{}).name||'Москва',tradable=code!=='plate_cool';state.plates.items.unshift({id:'store-'+order.id,number:String(number).toUpperCase(),region:{code:region,city:city,country:'Россия'},rarity:'secret',value:tradable?500000:0,createdAt:order.paidAt||Date.now(),attachedCarId:null,premium:true,tradable:tradable});}store.appliedOrderIds.push(order.id);store.appliedOrderIds=store.appliedOrderIds.slice(-200);if(!Array.isArray(store.history))store.history=[];store.history.unshift({id:order.id,title:order.title,productCode:code,paidAt:order.paidAt});store.history=store.history.slice(0,30);saveStore();return true;}
  async function syncStoreOrders(){var data=await request('/api/store/orders'),changed=false;(data.orders||[]).forEach(function(order){changed=applyOrder(order)||changed;});return changed;}
  async function checkStoreOrder(id){try{var data=await request('/api/store/orders?order='+encodeURIComponent(id));if(data.order.status==='paid'){applyOrder(data.order);localStorage.removeItem('autoflip-store-order');notice='Покупка успешно начислена аккаунту.';openStore();return true;}if(data.order.status==='canceled'){localStorage.removeItem('autoflip-store-order');notice='Платёж отменён. Деньги не списаны.';openStore();return true;}notice='Платёж обрабатывается. Обнови магазин через несколько секунд.';openStore();}catch(error){notice=errorText(error.message);openStore();}return false;}
  window.storeHistory=async function(){try{await syncStoreOrders();}catch(_){}var history=(ensureStore().history||[]);render('<div class="app store-app">'+head('Покупки')+'<section class="store-history-head"><small>AUTOFLIP STORE</small><h2>История покупок</h2></section>'+(history.length?'<div class="store-history">'+history.map(function(x){return '<div><span>✓</span><p><b>'+esc(x.title)+'</b><small>'+new Date(Number(x.paidAt||0)).toLocaleString('ru-RU')+'</small></p></div>';}).join('')+'</div>':'<div class="store-loading">Покупок пока нет</div>')+'<button class="action green" onclick="openStore()">В магазин</button></div>');};
  var canReadLocation=typeof URLSearchParams==='function'&&typeof location!=='undefined';
  var params=canReadLocation?new URLSearchParams(location.search):{get:function(){return null;}};
  var returnOrder=params.get('order')||(typeof localStorage!=='undefined'?localStorage.getItem('autoflip-store-order'):null);
  if(canReadLocation&&params.get('store')==='return'&&returnOrder){if(typeof history!=='undefined'&&history.replaceState)history.replaceState({},'',location.pathname);setTimeout(function(){checkStoreOrder(returnOrder);},350);}
  window.AUTOFLIP_STORE={applyOrder:applyOrder,activeBoost:activeBoost};
})();
